# Este es un archivo de configuración para el proyecto dbt llamado "advanced_dbt_project_v2". Define la estructura del proyecto, las rutas para los modelos, análisis, pruebas, semillas, macros y snapshots. También especifica la configuración de materialización y esquemas para diferentes capas de modelos (staging, intermediate y marts).
name: 'advanced_dbt_project_v2'
version: '1.0.0'
config-version: 2

# Se especifica el perfil de conexión a la base de datos que dbt utilizará para ejecutar los modelos y otras operaciones.
profile: 'advanced_dbt_project_v2'

# Se definen las rutas para los diferentes tipos de archivos en el proyecto, como modelos, análisis, pruebas, semillas, macros y snapshots.
model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

# Se especifica la ruta de destino para los archivos generados por dbt, como los modelos compilados y los resultados de las pruebas. También se definen los objetivos de limpieza para eliminar archivos generados previamente.
target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

# Se definen las configuraciones específicas para los modelos dentro del proyecto. Cada capa de modelos (staging, intermediate y marts) tiene su propia configuración de materialización y esquema.
models:
  advanced_dbt_project_v2:  
    staging:
      +materialized: table
      +schema: staging 
    intermediate:
      +materialized: view
      +schema: intermediate
    marts:
      +materialized: table 
      +schema: marts


