version: 2

models:
  - name: stg_orders
    columns:
      - name: status_code
        tests:
          - accepted_values:
              arguments: # List of accepted values for the status_code column
                values: ['P', 'O', 'F'] # P: Pending, O: Open, F: Fulfilled